from examples import PACKAGE_LOCATION

PANDAS_EX_LOCATION = PACKAGE_LOCATION / "pandas_ex"

DATA_LOCATION = PANDAS_EX_LOCATION / "data"


WORKER_DF_LOCATION = DATA_LOCATION / "worker.csv"
COMPANIES_DF_LOCATION = DATA_LOCATION / "companies.csv"
CITIES_DF_LOCATION = DATA_LOCATION / "cities.csv"